# Generated by Django 3.2.5 on 2021-07-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KospiData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kospi_date', models.DateTimeField()),
                ('conclusion', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('trade_value', models.IntegerField()),
            ],
        ),
    ]
