# Generated by Django 3.2.5 on 2021-07-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kospidata',
            name='conclusion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kospidata',
            name='kospi_date',
            field=models.CharField(max_length=50),
        ),
    ]
