# Generated by Django 3.2.5 on 2021-07-22 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210722_0402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kosdaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kospi_date', models.CharField(max_length=50)),
                ('conclusion', models.FloatField()),
                ('volume', models.IntegerField()),
                ('trade_value', models.IntegerField()),
            ],
        ),
    ]
