# Generated by Django 3.2.5 on 2021-07-22 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_kosdaq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kosdaq',
            old_name='kospi_date',
            new_name='kosdaq_date',
        ),
    ]
