# Generated by Django 3.2.5 on 2021-07-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capitalzation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockRank', models.IntegerField()),
                ('stockName', models.CharField(max_length=40)),
                ('stockPrice', models.IntegerField()),
                ('stockCap', models.IntegerField()),
                ('stockVolume', models.IntegerField()),
            ],
        ),
    ]
