# Generated by Django 3.2.5 on 2021-07-22 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_capitalzation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Capitalzation',
            new_name='CapitalzationKospi',
        ),
    ]
