# Generated by Django 3.2.5 on 2021-07-22 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_rename_capitalzation_capitalzationkospi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapitalzationKospi',
            new_name='Capitalzation',
        ),
    ]
