# Generated by Django 3.2.5 on 2021-07-14 21:56

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20210714_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
